# Form implementation generated from reading ui file 'voting.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(500, 500)
        MainWindow.setMinimumSize(QtCore.QSize(500, 500))
        MainWindow.setMaximumSize(QtCore.QSize(500, 500))
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.submit_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.submit_button.setGeometry(QtCore.QRect(190, 300, 121, 31))
        self.submit_button.setMaximumSize(QtCore.QSize(500, 500))
        self.submit_button.setObjectName("submit_button")
        self.result_text = QtWidgets.QLabel(parent=self.centralwidget)
        self.result_text.setGeometry(QtCore.QRect(50, 190, 401, 101))
        self.result_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.result_text.setObjectName("result_text")
        self.title = QtWidgets.QLabel(parent=self.centralwidget)
        self.title.setGeometry(QtCore.QRect(0, 0, 501, 141))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.title.setObjectName("title")
        self.candidate2_button = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.candidate2_button.setGeometry(QtCore.QRect(270, 140, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.candidate2_button.setFont(font)
        self.candidate2_button.setObjectName("candidate2_button")
        self.result_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.result_button.setGeometry(QtCore.QRect(190, 360, 121, 31))
        self.result_button.setObjectName("result_button")
        self.clear_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.clear_button.setGeometry(QtCore.QRect(190, 410, 121, 31))
        self.clear_button.setObjectName("clear_button")
        self.candidate1_button = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.candidate1_button.setGeometry(QtCore.QRect(140, 140, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.candidate1_button.setFont(font)
        self.candidate1_button.setObjectName("candidate1_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CandidateVoting"))
        self.submit_button.setText(_translate("MainWindow", "Submit Vote"))
        self.result_text.setText(_translate("MainWindow", "Please select one of the candidates to vote for."))
        self.title.setText(_translate("MainWindow", "Candidate Voting"))
        self.candidate2_button.setText(_translate("MainWindow", "Jane"))
        self.result_button.setText(_translate("MainWindow", "Results"))
        self.clear_button.setText(_translate("MainWindow", "Clear"))
        self.candidate1_button.setText(_translate("MainWindow", "John"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
