# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_login_page(object):
    def setupUi(self, login_page):
        login_page.setObjectName("login_page")
        login_page.resize(500, 500)
        login_page.setMinimumSize(QtCore.QSize(500, 500))
        login_page.setMaximumSize(QtCore.QSize(500, 500))
        font = QtGui.QFont()
        font.setPointSize(16)
        login_page.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=login_page)
        self.centralwidget.setObjectName("centralwidget")
        self.login_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.login_label.setGeometry(QtCore.QRect(210, 50, 131, 51))
        self.login_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.login_label.setObjectName("login_label")
        self.username_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.username_input.setGeometry(QtCore.QRect(280, 150, 113, 20))
        self.username_input.setObjectName("username_input")
        self.login_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.login_button.setGeometry(QtCore.QRect(190, 250, 151, 41))
        self.login_button.setObjectName("login_button")
        self.if_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.if_label.setGeometry(QtCore.QRect(70, 180, 161, 41))
        self.if_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.if_label.setObjectName("if_label")
        self.id_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.id_input.setGeometry(QtCore.QRect(280, 190, 113, 20))
        self.id_input.setObjectName("id_input")
        self.username_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.username_label.setGeometry(QtCore.QRect(130, 130, 101, 51))
        self.username_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.username_label.setObjectName("username_label")
        self.error_message = QtWidgets.QLabel(parent=self.centralwidget)
        self.error_message.setGeometry(QtCore.QRect(0, 360, 501, 31))
        self.error_message.setText("")
        self.error_message.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.error_message.setObjectName("error_message")
        login_page.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=login_page)
        self.statusbar.setObjectName("statusbar")
        login_page.setStatusBar(self.statusbar)

        self.retranslateUi(login_page)
        QtCore.QMetaObject.connectSlotsByName(login_page)

    def retranslateUi(self, login_page):
        _translate = QtCore.QCoreApplication.translate
        login_page.setWindowTitle(_translate("login_page", "Login Page"))
        self.login_label.setText(_translate("login_page", "LOGIN "))
        self.login_button.setText(_translate("login_page", "Login"))
        self.if_label.setText(_translate("login_page", "ID"))
        self.username_label.setText(_translate("login_page", "Username"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    login_page = QtWidgets.QMainWindow()
    ui = Ui_login_page()
    ui.setupUi(login_page)
    login_page.show()
    sys.exit(app.exec())
